//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Butler.Schema.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CalendarStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CalendarStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Butler.Schema.Resources.CalendarStrings", typeof(CalendarStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BYDAY only permitted once..
        /// </summary>
        internal static string ByDayOnlyPermittedOnce {
            get {
                return ResourceManager.GetString("ByDayOnlyPermittedOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BYHOUR only permitted once..
        /// </summary>
        internal static string ByHourOnlyPermittedOnce {
            get {
                return ResourceManager.GetString("ByHourOnlyPermittedOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BYHOUR value must be 0-23..
        /// </summary>
        internal static string ByHourOutOfRange {
            get {
                return ResourceManager.GetString("ByHourOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BYMINUTE only permitted once..
        /// </summary>
        internal static string ByMinuteOnlyPermittedOnce {
            get {
                return ResourceManager.GetString("ByMinuteOnlyPermittedOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BYMINUTE value must be 0-59..
        /// </summary>
        internal static string ByMinuteOutOfRange {
            get {
                return ResourceManager.GetString("ByMinuteOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BYMONTHDAY only permitted once..
        /// </summary>
        internal static string ByMonthDayOnlyPermittedOnce {
            get {
                return ResourceManager.GetString("ByMonthDayOnlyPermittedOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BYMONTHDAY value must be 1 to 31 or -1 to -31..
        /// </summary>
        internal static string ByMonthDayOutOfRange {
            get {
                return ResourceManager.GetString("ByMonthDayOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BYMONTH only permitted once..
        /// </summary>
        internal static string ByMonthOnlyPermittedOnce {
            get {
                return ResourceManager.GetString("ByMonthOnlyPermittedOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BYMONTH value must be 1 to 12..
        /// </summary>
        internal static string ByMonthOutOfRange {
            get {
                return ResourceManager.GetString("ByMonthOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BYSECOND only permitted once..
        /// </summary>
        internal static string BySecondOnlyPermittedOnce {
            get {
                return ResourceManager.GetString("BySecondOnlyPermittedOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BYSECOND value must be 0-59..
        /// </summary>
        internal static string BySecondOutOfRange {
            get {
                return ResourceManager.GetString("BySecondOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BYSETPOS only permitted once..
        /// </summary>
        internal static string BySetPosOnlyPermittedOnce {
            get {
                return ResourceManager.GetString("BySetPosOnlyPermittedOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BYSETPOS value must be 1 to 366 or -1 to -366..
        /// </summary>
        internal static string BySetPosOutOfRange {
            get {
                return ResourceManager.GetString("BySetPosOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BYWEEKNO only permitted once..
        /// </summary>
        internal static string ByWeekNoOnlyPermittedOnce {
            get {
                return ResourceManager.GetString("ByWeekNoOnlyPermittedOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BYWEEKNO value must be 1 to 53 or -1 to -53..
        /// </summary>
        internal static string ByWeekNoOutOfRange {
            get {
                return ResourceManager.GetString("ByWeekNoOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BYYEARDAY only permitted once..
        /// </summary>
        internal static string ByYearDayOnlyPermittedOnce {
            get {
                return ResourceManager.GetString("ByYearDayOnlyPermittedOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BYYEARDAY value must be 1 to 366 or -1 to -366..
        /// </summary>
        internal static string ByYearDayOutOfRange {
            get {
                return ResourceManager.GetString("ByYearDayOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t start on a property..
        /// </summary>
        internal static string CannotStartOnProperty {
            get {
                return ResourceManager.GetString("CannotStartOnProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t start a property in a parameter..
        /// </summary>
        internal static string CannotStartPropertyInParameter {
            get {
                return ResourceManager.GetString("CannotStartPropertyInParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component name mismatch..
        /// </summary>
        internal static string ComponentNameMismatch {
            get {
                return ResourceManager.GetString("ComponentNameMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count &lt; 0..
        /// </summary>
        internal static string CountLessThanZero {
            get {
                return ResourceManager.GetString("CountLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COUNT not permitted with UNTIL..
        /// </summary>
        internal static string CountNotPermittedWithUntil {
            get {
                return ResourceManager.GetString("CountNotPermittedWithUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COUNT only permitted once..
        /// </summary>
        internal static string CountOnlyPermittedOnce {
            get {
                return ResourceManager.GetString("CountOnlyPermittedOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration data not ended properly..
        /// </summary>
        internal static string DurationDataNotEndedProperly {
            get {
                return ResourceManager.GetString("DurationDataNotEndedProperly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component name cannot be empty..
        /// </summary>
        internal static string EmptyComponentName {
            get {
                return ResourceManager.GetString("EmptyComponentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty parameter name..
        /// </summary>
        internal static string EmptyParameterName {
            get {
                return ResourceManager.GetString("EmptyParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property name is empty..
        /// </summary>
        internal static string EmptyPropertyName {
            get {
                return ResourceManager.GetString("EmptyPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to END tag without BEGIN..
        /// </summary>
        internal static string EndTagWithoutBegin {
            get {
                return ResourceManager.GetString("EndTagWithoutBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did not find H, M, or S to terminate integer..
        /// </summary>
        internal static string ExpectedHMS {
            get {
                return ResourceManager.GetString("ExpectedHMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did not find M to terminate integer..
        /// </summary>
        internal static string ExpectedM {
            get {
                return ResourceManager.GetString("ExpectedM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected P after + or -..
        /// </summary>
        internal static string ExpectedP {
            get {
                return ResourceManager.GetString("ExpectedP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected +/- at start of offset..
        /// </summary>
        internal static string ExpectedPlusMinus {
            get {
                return ResourceManager.GetString("ExpectedPlusMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did not find S to terminate integer..
        /// </summary>
        internal static string ExpectedS {
            get {
                return ResourceManager.GetString("ExpectedS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T expected..
        /// </summary>
        internal static string ExpectedT {
            get {
                return ResourceManager.GetString("ExpectedT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected T after date..
        /// </summary>
        internal static string ExpectedTAfterDate {
            get {
                return ResourceManager.GetString("ExpectedTAfterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did not find W or D to terminate integer..
        /// </summary>
        internal static string ExpectedWOrD {
            get {
                return ResourceManager.GetString("ExpectedWOrD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected Z at end of UTC time..
        /// </summary>
        internal static string ExpectedZ {
            get {
                return ResourceManager.GetString("ExpectedZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval must be a positive integer..
        /// </summary>
        internal static string IntervalMustBePositive {
            get {
                return ResourceManager.GetString("IntervalMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INTERVAL only permitted once..
        /// </summary>
        internal static string IntervalOnlyPermittedOnce {
            get {
                return ResourceManager.GetString("IntervalOnlyPermittedOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid character in string..
        /// </summary>
        internal static string InvalidCharacter {
            get {
                return ResourceManager.GetString("InvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid character in parameter name..
        /// </summary>
        internal static string InvalidCharacterInParameterName {
            get {
                return ResourceManager.GetString("InvalidCharacterInParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid character in parameter text..
        /// </summary>
        internal static string InvalidCharacterInParameterText {
            get {
                return ResourceManager.GetString("InvalidCharacterInParameterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid character in property name..
        /// </summary>
        internal static string InvalidCharacterInPropertyName {
            get {
                return ResourceManager.GetString("InvalidCharacterInPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid character in property value..
        /// </summary>
        internal static string InvalidCharacterInPropertyValue {
            get {
                return ResourceManager.GetString("InvalidCharacterInPropertyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid character in quoted string..
        /// </summary>
        internal static string InvalidCharacterInQuotedString {
            get {
                return ResourceManager.GetString("InvalidCharacterInQuotedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid character in recurrence..
        /// </summary>
        internal static string InvalidCharacterInRecurrence {
            get {
                return ResourceManager.GetString("InvalidCharacterInRecurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid component ID..
        /// </summary>
        internal static string InvalidComponentId {
            get {
                return ResourceManager.GetString("InvalidComponentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date format..
        /// </summary>
        internal static string InvalidDateFormat {
            get {
                return ResourceManager.GetString("InvalidDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid length for DateTime..
        /// </summary>
        internal static string InvalidDateTimeLength {
            get {
                return ResourceManager.GetString("InvalidDateTimeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameter ID..
        /// </summary>
        internal static string InvalidParameterId {
            get {
                return ResourceManager.GetString("InvalidParameterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameter value..
        /// </summary>
        internal static string InvalidParameterValue {
            get {
                return ResourceManager.GetString("InvalidParameterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid property ID..
        /// </summary>
        internal static string InvalidPropertyId {
            get {
                return ResourceManager.GetString("InvalidPropertyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation is not allowed in current reader state..
        /// </summary>
        internal static string InvalidReaderState {
            get {
                return ResourceManager.GetString("InvalidReaderState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid state encountered..
        /// </summary>
        internal static string InvalidState {
            get {
                return ResourceManager.GetString("InvalidState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid state for operation..
        /// </summary>
        internal static string InvalidStateForOperation {
            get {
                return ResourceManager.GetString("InvalidStateForOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid state to write a value..
        /// </summary>
        internal static string InvalidStateToWriteValue {
            get {
                return ResourceManager.GetString("InvalidStateToWriteValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid time format..
        /// </summary>
        internal static string InvalidTimeFormat {
            get {
                return ResourceManager.GetString("InvalidTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid length for time string..
        /// </summary>
        internal static string InvalidTimeStringLength {
            get {
                return ResourceManager.GetString("InvalidTimeStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token in data..
        /// </summary>
        internal static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid length for UtcOffset data..
        /// </summary>
        internal static string InvalidUtcOffsetLength {
            get {
                return ResourceManager.GetString("InvalidUtcOffsetLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value format..
        /// </summary>
        internal static string InvalidValueFormat {
            get {
                return ResourceManager.GetString("InvalidValueFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value type for property..
        /// </summary>
        internal static string InvalidValueTypeForProperty {
            get {
                return ResourceManager.GetString("InvalidValueTypeForProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multivalue not permitted on COUNT..
        /// </summary>
        internal static string MultivalueNotPermittedOnCount {
            get {
                return ResourceManager.GetString("MultivalueNotPermittedOnCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multivalue not permitted on FREQ..
        /// </summary>
        internal static string MultivalueNotPermittedOnFreq {
            get {
                return ResourceManager.GetString("MultivalueNotPermittedOnFreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multivalue not permitted on INTERVAL..
        /// </summary>
        internal static string MultivalueNotPermittedOnInterval {
            get {
                return ResourceManager.GetString("MultivalueNotPermittedOnInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multivalue not permitted on UNTIL..
        /// </summary>
        internal static string MultivalueNotPermittedOnUntil {
            get {
                return ResourceManager.GetString("MultivalueNotPermittedOnUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multivalue not permitted on WKST..
        /// </summary>
        internal static string MultivalueNotPermittedOnWkSt {
            get {
                return ResourceManager.GetString("MultivalueNotPermittedOnWkSt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-writable stream..
        /// </summary>
        internal static string NonwritableStream {
            get {
                return ResourceManager.GetString("NonwritableStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all components were closed correctly..
        /// </summary>
        internal static string NotAllComponentsClosed {
            get {
                return ResourceManager.GetString("NotAllComponentsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset &lt; 0 or offset &gt; buffer.Length..
        /// </summary>
        internal static string OffsetOutOfRange {
            get {
                return ResourceManager.GetString("OffsetOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter name is missing..
        /// </summary>
        internal static string ParameterNameMissing {
            get {
                return ResourceManager.GetString("ParameterNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters are not permitted on a component tag..
        /// </summary>
        internal static string ParametersNotPermittedOnComponentTag {
            get {
                return ResourceManager.GetString("ParametersNotPermittedOnComponentTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter values cannot contain a double quote character..
        /// </summary>
        internal static string ParameterValuesCannotContainDoubleQuote {
            get {
                return ResourceManager.GetString("ParameterValuesCannotContainDoubleQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A property was found that is not inside any component..
        /// </summary>
        internal static string PropertyOutsideOfComponent {
            get {
                return ResourceManager.GetString("PropertyOutsideOfComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of property..
        /// </summary>
        internal static string PropertyTruncated {
            get {
                return ResourceManager.GetString("PropertyTruncated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State must be component..
        /// </summary>
        internal static string StateMustBeComponent {
            get {
                return ResourceManager.GetString("StateMustBeComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream has already been closed..
        /// </summary>
        internal static string StreamHasAlreadyBeenClosed {
            get {
                return ResourceManager.GetString("StreamHasAlreadyBeenClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a read-only stream..
        /// </summary>
        internal static string StreamIsReadOnly {
            get {
                return ResourceManager.GetString("StreamIsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream must support read..
        /// </summary>
        internal static string StreamMustAllowRead {
            get {
                return ResourceManager.GetString("StreamMustAllowRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream must support write..
        /// </summary>
        internal static string StreamMustAllowWrite {
            get {
                return ResourceManager.GetString("StreamMustAllowWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of stream..
        /// </summary>
        internal static string UnexpectedEndOfStream {
            get {
                return ResourceManager.GetString("UnexpectedEndOfStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown day of week..
        /// </summary>
        internal static string UnknownDayOfWeek {
            get {
                return ResourceManager.GetString("UnknownDayOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown frequency value..
        /// </summary>
        internal static string UnknownFrequencyValue {
            get {
                return ResourceManager.GetString("UnknownFrequencyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Recurrence property..
        /// </summary>
        internal static string UnknownRecurrenceProperty {
            get {
                return ResourceManager.GetString("UnknownRecurrenceProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNTIL not permitted with COUNT..
        /// </summary>
        internal static string UntilNotPermittedWithCount {
            get {
                return ResourceManager.GetString("UntilNotPermittedWithCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNTIL only permitted once..
        /// </summary>
        internal static string UntilOnlyPermittedOnce {
            get {
                return ResourceManager.GetString("UntilOnlyPermittedOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timespan for UTCOffset cannot contain days..
        /// </summary>
        internal static string UtcOffsetTimespanCannotContainDays {
            get {
                return ResourceManager.GetString("UtcOffsetTimespanCannotContainDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value has already been read..
        /// </summary>
        internal static string ValueAlreadyRead {
            get {
                return ResourceManager.GetString("ValueAlreadyRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WKST only permitted once..
        /// </summary>
        internal static string WkStOnlyPermittedOnce {
            get {
                return ResourceManager.GetString("WkStOnlyPermittedOnce", resourceCulture);
            }
        }
    }
}
